apiVersion: v1
kind: PersistentVolume
metadata:
  name: awsvol
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-aa3e602a
    fsType: ext4
