apiVersion: v1
kind: PersistentVolume
metadata:
  name: flex-nfs-vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "rancher.io/myFlexNFS"
    options:
      server: "146.148.46.118"
      path: "/var/nfs"
