apiVersion: v1
kind: Pod
metadata:
  name: flex
spec:
  containers:
  - name: flex
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "rancher.io/myFlexNFS"
      options:
        server: "146.148.46.118"
        path: "/var/nfs"
