apiVersion: v1
kind: Pod
metadata:
  name: flex
spec:
  containers:
  - name: flex
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    persistentVolumeClaim:
     claimName: myclaim-flex-nfs
